config/routes.rb
Kiwitime::Application.routes.draw do

  resources :sprints do
    resources :workings
  end

  devise_scope :user do
    get 'users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/p/:project_id/tasks" => redirect("/p/%{project_id}")
  get "/p/:project_id/tasks/:task_id/sittings" => redirect("/p/%{project_id}/tasks/%{task_id}")

  resources :users, path: 'u' do
    get 'page/:page' => :index, on: :collection
    post 'rol' => :set_rol, on: :member
    delete 'rol' => :set_rol, on: :member
  end

  resources :tasks, only: [] do
    post :sort, on: :collection
  end

  resources :projects, path: 'p' do
    post 'rol' => :set_rol, on: :member
    delete 'rol' => :delete_rol, on: :member
    resources :tasks do
      post :suggest, on: :collection
      resources :sittings
      resources :comments, except: :index
      member do
        get 'finish'
        get 'reject'
        get 'start'
        get 'stop'
        get 'up'
        get 'accept'
      end
    end

    member do
      get 'report'
      get 'sprint/:sprint_id' => :sprint, as: :sprint
    end
  end

  authenticated do
    root to: "projects#index"
  end

  devise_scope :user do
    root :to => "pages#home"
  end

end

app/models/working.rb
# == Schema Information
#
# Table name: workings
#
#  id         :integer          not null, primary key
#  sprint_id  :integer
#  day        :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  points     :float
#

class Working < ActiveRecord::Base
  attr_accessible :day, :sprint_id, :points
  belongs_to :sprint
  default_scope :order => 'workings.day ASC'
end

app/controllers/workings_controller.rb
class WorkingsController < ApplicationController
  load_and_authorize_resource :sprint
  load_and_authorize_resource :working, :through => :sprint

  # GET /workings
  # GET /workings.json
  def index
    @workings = Working.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @workings }
    end
  end

  # GET /workings/1
  # GET /workings/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @working }
    end
  end

  # GET /workings/new
  # GET /workings/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @working }
    end
  end

  # GET /workings/1/edit
  def edit
  end

  # POST /workings
  # POST /workings.json
  def create
    respond_to do |format|
      if @working.save
        format.html { redirect_to sprints_path, notice: 'Working was successfully created.' }
        format.json { render json: @working, status: :created, location: @working }
      else
        format.html { render action: "new" }
        format.json { render json: @working.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workings/1
  # PUT /workings/1.json
  def update
    respond_to do |format|
      if @working.update_attributes(params[:working])
        format.html { redirect_to @working, notice: 'Working was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @working.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workings/1
  # DELETE /workings/1.json
  def destroy
    @working.destroy

    respond_to do |format|
      format.html { redirect_to sprints_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/workings_helper.rb
module WorkingsHelper
end

app/views/workings/_form.html.haml
= form_for([@sprint, @working]) do |f|
  - if @working.errors.any?
    #error_explanation
      %h2
        = pluralize(@working.errors.count, "error")
        prohibited this working from being saved:
      %ul
        - @working.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :day
    .datepicker
      = f.text_field :day
  .actions
    = f.submit

app/views/workings/edit.html.erb
<h1>Editing working</h1>

<%= render 'form' %>

<%= link_to 'Show', @working %> |
<%= link_to 'Back', workings_path %>

app/views/workings/index.html.erb
<h1>Listing workings</h1>

<table>
  <tr>
    <th>Id sprint</th>
    <th>Day</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @workings.each do |working| %>
  <tr>
    <td><%= working.sprint_id %></td>
    <td><%= working.day %></td>
    <td><%= link_to 'Show', [@sprint,working] %></td>
    <td><%= link_to 'Edit', edit_sprint_working_path(@sprint, working) %></td>
    <td><%= link_to 'Destroy', [@sprint, working], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Working', new_sprint_working_path(@sprint) %>

app/views/workings/new.html.erb
<h1>New working</h1>

<%= render 'form' %>

<%= link_to 'Back', sprint_workings_path  %>

app/views/workings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Day:</b>
  <%= @working.day %>
</p>


<%= link_to 'Edit', edit_sprint_working_path(@sprint, @working) %> |
<%= link_to 'Back', (sprint_workings_path @sprint) %>