config/routes.rb
Kiwitime::Application.routes.draw do

  resources :sprints do
    resources :workings
  end

  devise_scope :user do
    get 'users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/p/:project_id/tasks" => redirect("/p/%{project_id}")
  get "/p/:project_id/tasks/:task_id/sittings" => redirect("/p/%{project_id}/tasks/%{task_id}")

  resources :users, path: 'u' do
    get 'page/:page' => :index, on: :collection
    post 'rol' => :set_rol, on: :member
    delete 'rol' => :set_rol, on: :member
  end

  resources :tasks, only: [] do
    post :sort, on: :collection
  end

  resources :projects, path: 'p' do
    post 'rol' => :set_rol, on: :member
    delete 'rol' => :delete_rol, on: :member
    resources :tasks do
      post :suggest, on: :collection
      resources :sittings
      resources :comments, except: :index
      member do
        get 'finish'
        get 'reject'
        get 'start'
        get 'stop'
        get 'up'
        get 'accept'
      end
    end

    member do
      get 'report'
      get 'sprint/:sprint_id' => :sprint, as: :sprint
    end
  end

  authenticated do
    root to: "projects#index"
  end

  devise_scope :user do
    root :to => "pages#home"
  end

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  project_id  :integer
#  finished    :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  position    :integer
#  sprint_id   :integer
#  points      :float
#  status      :string(255)
#  category    :string(255)      default("feature")
#

class Task < ActiveRecord::Base
  acts_as_list

  POINTS = [0.0, 0.5, 1.0, 2.0, 3.0, 5.0, 8.0, 13.0, 20.0, 40.0]
  #CATEGORIES = [ :feature, :bug, :chore, :release ]
  CATEGORIES = [ :feature, :bug, :chore ]

  attr_accessible :id,:description, :finished, :name, :project_id, :points, :sprint_id, :category

  belongs_to :project
  belongs_to :sprint

  has_many :sittings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :users,  :through => :sittings


  validates :name, presence: true
  validates :project_id, presence: true
  validates :points, :inclusion => { :in => [nil, 0, 0.0, "0"]}, :if => :no_puntuable

  default_scope :order => 'tasks.position ASC'

  scope :icebox, lambda{ where(sprint_id: nil) }
  scope :by_sprint_id, lambda{|sprint_id| where(sprint_id: sprint_id)}
  scope :by_sprint, lambda{|sprint| sprint ? by_sprint_id(sprint.id) : where(0)}
  scope :current, lambda{by_sprint Sprint.current}
  #(day && t.finish_at) ? ((t.finish_at < day) ? t.points : 0) : 0}.sum }

  after_update :move_to_bottom_if_sprint_is_changed

  def move_to_bottom_if_sprint_is_changed
    # comprobamos que no sea el ultimo para no provocar un bucle infinito
    if sprint_id_changed? && Task.last != self && !position_changed?
      move_to_bottom
    end
  end
  

  def in_progress?
    sittings.any? { |sitting| sitting.in_progress? }
  end

  def in_progress_for_user?(user)
    sittings.any? { |sitting| sitting.in_progress? && sitting.user == user}
  end

  def delta
    sittings.sum{|sitting| sitting.delta}
  end

  def finish_at
    finished && (sittings.collect{|s| s.day}.select{|s| s}.max || updated_at.to_date)
  end

  def finished_at(day)
    finish_at && finish_at <= day
  end

  def no_puntuable
    ["chore", "bug", "release"].include?(category)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource :project, except: :sort
  load_and_authorize_resource :task, through: :project, except: :sort

  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  def sort
    @tasks = Task.all
    @tasks.each do |task|
      index = params['task'].index(task.id.to_s)
      if index
        task.position = params['task'].index(task.id.to_s) + 1
        task.save
      end 
    end

    render :nothing => true
  end


  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @comment = Comment.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    respond_to do |format|
      if @task.save
        format.html { redirect_to [@project], notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /tasks
  # POST /tasks.json
  def suggest
    @task = @project.tasks.create params[:task]
    respond_to do |format|
      if @task.save
        format.html { redirect_to [@project], notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { redirect_to :back, alert: 'Task can\'t be created.'}
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to :back, notice: 'Task was successfully updated.'}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to project_tasks_url }
      format.json { head :no_content }
    end
  end

  def finish
    @task.finished = true
    @task.save
    @task.sittings.each do |sitting| 
      if sitting.in_progress?
        sitting.end = Time.now
        sitting.save
      end
    end
    redirect_to :back, notice: 'Task stopped and finished.'
  end

  def reject
    @task.status = "reject"
    @task.finished = false
    #@task.sprint = nil
    @task.save
    comment = @task.comments.build
    comment.message = "Reject!"
    comment.user = current_user
    comment.save
    redirect_to :back, notice: 'Task is rejected'
  end

  def up
    @task.sprint = Sprint.current
    @task.save
    redirect_to :back, notice: 'Task is up to sprint!'
  end

  def accept
    @task.status = "accept"
    @task.save
    redirect_to :back, notice: 'Task is Accepted!'
  end

  def start
    #@task = Task.find(params[:id])
    #p = {"task_id"=>params[:id], "day(1i)"=>"2012", "day(2i)"=>"11", "day(3i)"=>"6", "start(1i)"=>"2012", "start(2i)"=>"11", "start(3i)"=>"6", "start(4i)"=>"20", "start(5i)"=>"36", "end(1i)"=>"1", "end(2i)"=>"1", "end(3i)"=>"1", "end(4i)"=>"", "end(5i)"=>""}
    p = {"task_id"=>params[:id], day: Time.now, start:Time.now}
    sitting = current_user.sittings.build({task_id: params[:id], start: Time.now, day: Time.now})
    sitting.save
    redirect_to :back, notice: 'Task started.'
  end

  def stop
    @task.sittings.each do |sitting| 
      if sitting.user == current_user && sitting.in_progress?
        sitting.end = Time.now
        sitting.message = params[:message]
        sitting.save
      end
    end
    @task.save
    redirect_to :back, notice: 'Task stopped.'
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
= form_for([@project, @task]) do |f|
  - if @task.errors.any?
    #error_explanation
      %h2
        = pluralize(@task.errors.count, "error")
        prohibited this task from being saved:
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name, class: 'span6'
  .field
    = f.label :description
    = f.text_area :description, :size => "25x5", class: 'span6'
  .field
    = f.label :sprint_id, "Sprint"
    = f.select(:sprint_id, Sprint.all.collect{|s| [s, s.id]}, :prompt => true, :include_blank => 'Icebox')
  .field
    = f.label :points
    =# f. :points, class: 'span1'
    = f.select(:points, Task::POINTS.collect{|n| ["%g" % n, n]}, {:include_blank => true})
    points
  .field
    = f.label :category
    = f.select(:category, Task::CATEGORIES)
  .field
    %label.checkbox
      = f.check_box :finished
      Finished


  .actions
    = f.submit

app/views/tasks/_task.html.haml
= content_tag_for :div, task, class: "task row #{task.finished ? 'muted' : ''} #{task.status}" do
  - if (defined? sortable) && sortable
    -if can? :sort, task
      .handle
  - #%div{class: task.finished && "row muted" || "row"}

  .span1.mini-avatars
    - task.users.accessible_by(current_ability).uniq.each do |user|
      = gravatar_for user, size:20
  .span4.name
    %a{href:project_task_path(task.project, task)}
      = image_tag("#{task.category||'feature'}.png", alt: task.category)
      %small= "##{task.id} -"
      = task.name.truncate(60)
      -# %small (#{task.sittings.sum{|s| s.delta}} of #{pluralize(task.points, 'point')})
    -if (params[:controller] == "projects")
      %small= task.description.truncate(60, separator: ' ')
    -else
      %small on #{link_to(task.project, task.project)}
    -if task.finished
      %i.icon-ok.icon-gray

  .pull-right.trash
    %a{"data-confirm" => "Are you sure?", "data-method" => "delete", href: project_task_path(task.project, task), rel: "nofollow"}
      %i.icon-trash

  .pull-right
    .grey-points
      %span.actual
        - if ["release", "chore", "bug"].exclude?(task.category)
          = task.points ? "%g" % task.points : "?"
          - if  can? :update, task && task.status != 'accept' 
            %span.options
              = link_to "?", project_task_path(task.project, task, task: {"points" => nil}), :method => :put, :class => "input-grey-points"
              - Task::POINTS.each do |n|
                = link_to "%g" % n, project_task_path(task.project, task, task: {"points" => n}), :method => :put, :class => "input-grey-points"
        - else
          &nbsp;

  -if can? :update, task
    .btn-group.pull-right
      -if (defined? icebox) && icebox
        -if @sprint
          %a.btn.btn-inverse{href: project_task_path(task.project, task, task: {"sprint_id" => @sprint.id}), "data-method" => :put}
            %i.icon-arrow-up.icon-white
            Up to current sprint
      -elsif task.status == "accept"
      -else
        - if task.finished
        - else
          -if task.in_progress_for_user?(current_user)
            %form{action: stop_project_task_path(task.project, task), class: "form-inline"}
              .input-append
                %input.input-span2{type: "text", name:"message", placeholder: 'Describe your job here'}
                  %button.btn.btn-danger{:type => "submit"}
                    %i.icon-stop.icon-white
                    stop
          -else
            %a.btn.btn-success(href='#{start_project_task_path(task.project, task)}')
              %i.icon-play.icon-white
              Start
            %a.btn.btn-inverse(href='#{finish_project_task_path(task.project, task)}')
              %i.icon-check.icon-white
              /Finish Him!
              Deliver

  .pull-right
    -if task.status != "accept"
      - if task.finished
        -if can? :accept, task
          /%a.btn.btn-inverse{href:reopen_project_task_path(task.project, task)}
          /  %i.icon-repeat.icon-white
          /  Re-open
          %a.btn.btn-success(href='#{accept_project_task_path(task.project, task)}')
            %i.icon-ok-circle.icon-white
            Accept
          %a.btn.btn-danger(href='#{reject_project_task_path(task.project, task)}')
            %i.icon-ban-circle.icon-white
            Reject

app/views/tasks/edit.html.haml
%h2 Editing task
= render 'form'
= link_to 'Show', project_task_path(@project, @task)
|
\#{link_to 'Back', project_tasks_path}

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Time scope</th>
    <th>Project</th>
    <th>Finished</th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= link_to task.name, project_task_path(@project, task) %></td>
    <td><%= task.description %></td>
    <td><%= pluralize(task.points, 'point') %></td>
    <td><%= task.project_id %></td>
    <td><%= task.finished %></td>
    <td><%= link_to 'Edit', edit_project_task_path(@project, task) %></td>
    <td><%= link_to 'Destroy', [@project, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_project_task_path %>

app/views/tasks/new.html.haml
%h2 New task
= render 'form'
= link_to 'Back', project_tasks_path

app/views/tasks/show.html.haml
.page-header
  %h2
    %small
      .btn-group.pull-right
        -if can? :update, @task
          %a.btn.btn-warning{href: edit_project_task_path(@project, @task)}
            %i.icon-pencil.icon-white
            Edit
        -if can? :destroy, @task
          %a.btn.btn-danger{"data-confirm" => "Are you sure?", "data-method" => "delete", href: project_task_path(@project, @task), rel: "nofollow"}
            %i.icon-remove.icon-white
            Delete
    %span{class:('completedtask' if @task.finished)}
      \ ##{@task.id} - #{@task.name} 
      /%i.icon-ok{style:'opacity:0.3'}
      %small 
        ( on 
        %a{href:project_tasks_path}=@task.project && @task.project.name 
        )


    %small
      .muted
        = raw sanitize mkd.render @task.description
.row
  .span5.comments
    %h4.page-header Comments
    - @task.comments.each do |comment|
      .row
        .span5.comment
          -if can? :destroy, comment
            .pull-right
              %a{"data-confirm" => "Are you sure?", "data-method" => "delete", href: project_task_comment_path(@project, @task, comment), rel: "nofollow"}
                %i.icon-remove
          %b
            = comment.user
          = (simple_format comment.message) 
          .muted
            = comment.created_at.to_s(:short)
    .form-actions
      = form_for([@project, @task, @comment], html:{class: "form-inline"}) do |f|
        =# form_for(@comment, :url => project_task_comments_path(@project, @task, @comment), :method => :post,  :html => { :class => "form-inline"}) do |f|
        - if @comment.errors.any?
          #error_explanation
            %h2
              = pluralize(@comment.errors.count, "error")
              prohibited this comment from being saved:
            %ul
              - @comment.errors.full_messages.each do |msg|
                %li= msg

        .field
          = f.text_area :message, class: "span3", rows:3
          = f.submit class: "span1", value: "Send"

        -#  .field
        -#    = f.label :init
        -#    = f.date_select :init
        -#  .field
        -#    = f.label :finish
        -#    = f.date_select :finish
        -#  .field
        -#    = f.label :notas
        -#    = f.text_field :notas
        -#  .actions
        -#    = f.submit



  -if can? :index, Sitting
    .span4
      %h4.page-header Sittings
      =render @task.sittings
      .row
        .pull-right
          -if can? :create, @task.sittings.build
            %a{href: new_project_task_sitting_path(@project, @task, @sitting), class:'btn btn-primary btn-small'} New Sitting

app/views/tasks/update.js.erb
// we could highlight the checkbox to show it's been clicked:
$('#thing').css("color","yellow");

// or add the updated thing to a list:
$('#things').prepend('<%=escape_javascript render(@thing) %>');