config/routes.rb
Kiwitime::Application.routes.draw do

  resources :sprints do
    resources :workings
  end

  devise_scope :user do
    get 'users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/p/:project_id/tasks" => redirect("/p/%{project_id}")
  get "/p/:project_id/tasks/:task_id/sittings" => redirect("/p/%{project_id}/tasks/%{task_id}")

  resources :users, path: 'u' do
    get 'page/:page' => :index, on: :collection
    post 'rol' => :set_rol, on: :member
    delete 'rol' => :set_rol, on: :member
  end

  resources :tasks, only: [] do
    post :sort, on: :collection
  end

  resources :projects, path: 'p' do
    post 'rol' => :set_rol, on: :member
    delete 'rol' => :delete_rol, on: :member
    resources :tasks do
      post :suggest, on: :collection
      resources :sittings
      resources :comments, except: :index
      member do
        get 'finish'
        get 'reject'
        get 'start'
        get 'stop'
        get 'up'
        get 'accept'
      end
    end

    member do
      get 'report'
      get 'sprint/:sprint_id' => :sprint, as: :sprint
    end
  end

  authenticated do
    root to: "projects#index"
  end

  devise_scope :user do
    root :to => "pages#home"
  end

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name
  resourcify

  attr_accessible :name
  has_many :tasks, dependent: :destroy

  def delta
    tasks.sum{|task| task.delta}
  end

  def serializable_hash(options={})
    options = { 
      include: {
        tasks: {
          sittings: {
            user: {}
          }
        }
      }
    }.update(options)
    super(options)
  end

  def to_s
    name.humanize
  end

  def points_finished
    @points_finished ||= (tasks.collect{|t| t.finished ? (t.points||0) : 0 }).sum
  end

  def total_points
    @total_points ||= (tasks.collect{|t| t.points||0}).sum
  end

  def total_points_by_sprint(sprint)
    (tasks.by_sprint(sprint).collect{|t| t.points||0}).sum
  end

  def current_total_points
    @current_total_points ||= total_points_by_sprint(Sprint.current)
  end

  def stats(sprint)
    if sprint
      tp = total_points_by_sprint(sprint)
      workings_days = sprint.workings
      days = workings_days.count
      n = 0
      (workings_days).collect do |w|
        n += 1
        d = w.day
        [
          d.strftime("%a, %d %b"),
          (Time.now >= d) ? (tp - tasks.select{|t| (t.finished_at d) && t.sprint_id == sprint.id }.collect{|t| t.points || 0}.sum) : nil,
          (tp * (days - n) / (days)).to_f,
        ]
      end
    end
  end

  def product_owners
    rol = roles.find_by_name("product_owner")
    rol ? rol.users : []
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  load_and_authorize_resource :sprint, :only => :sprint

  respond_to :html, :json
  layout false, only: :report

  # GET /projects
  # GET /projects.json
  def index
    @projects = @projects.includes(:tasks).all
    respond_with(@projects)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @sprint = Sprint.current
    @task_current_sprint = @project.tasks.current
    @chart = current_chart if @sprint
    respond_with(@project)
  end

  def sprint
    @task_current_sprint = @project.tasks.by_sprint_id(params[:sprint_id])
    @chart = chart(@sprint)
    #render :template => 'projects/show'

    respond_to do |format|
      format.json {respond_with(@project)}
      format.html {render :action => 'show'}
    end
    
  end

  def chart(sprint)
    data = @project.stats(sprint)
    if data[0] && data[0][1].present?
      data_table = GoogleVisualr::DataTable.new
      # Add Column Headers 
      data_table.new_column('string', 'Day' ) 
      data_table.new_column('number', 'Actual') 
      data_table.new_column('number', 'Scope')
      # Add Rows and Values 
      data_table.add_rows(data)
      option = { width: 800, height: 400, title: "#{@project} #{sprint}", legend: {position: "none"} }
      GoogleVisualr::Interactive::LineChart.new(data_table, option)
    end
  end

  def current_chart
    chart(Sprint.current)
  end

  def report
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end


  def set_rol
    User.find(params[:user]).add_role params[:rol], @project
    redirect_to :back, notice: 'Rol changed.'
  end

  def delete_rol
    User.find(params[:user]).remove_role params[:rol], @project
    redirect_to :back, notice: 'Rol changed.'
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.haml
%h2 Projects
%ul.unstyled.projects-list
  - @projects.each do |project|
    %li.projects-project
      .pull-right
        .progress.span5
          -if project.total_points > 0
            .bar.bar-success{style: "width: #{project.points_finished * 100 / project.total_points}%;"}
          //.bar.bar-warning{style:"width: #{(project.tasks.collect{|t| t.in_progress?}).count(true) * 100 / project.tasks.count}%;"}
        .span1
          \#{(project.tasks.collect{|t| t.finished ? (t.points||0) : 0 }).sum()}
          \/
          = (project.tasks.collect{|t| t.points||0 }).sum()
      %h4
        = link_to project.name, project, class: 'projects-project-name'

%br

-if can? :create, Project
  %br
  .pull-right
    %a.btn.btn-primary(href=new_project_path) New Project

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/report.html.haml
%style
  \body{width:45em;margin:auto;background:#EEE;font-family:georgia}
  \.list{margin:1ex 1.5em;padding:1ex .5em;border-left:.2em solid whiteSmoke:rgba(220,240,160,.5)}
  \.container{background:white;color:black;padding:2ex 2em;margin:1em 0;}
  \h2{border-bottom:1px solid #DDD}
  \h1{text-align:center;margin-bottom:2em}
  \.sitting:after{content:":"}
  \.sitting:empty:after{content:""}
  \.footer{background:#F5F5F5; padding:2ex 1em;text-align:right}


.container
  .page-header
    %h1=@project.name
    %div
      - @project.tasks.each do |task|
        -unless task.delta == 0
          %header
            %h2 
              %b
                #{task.name}
              (#{pluralize(task.delta, 'minute')})
            %div
              -unless task.description.empty?
                %b
                  =task.description
              %div.list
                - task.sittings.each do |sitting|
                  -if sitting.delta > 0
                    %div
                      %b.sitting #{sitting.message}
                      #{pluralize(sitting.delta, 'minute')}
  %br
  .footer
    %b
      Total time:
    =pluralize(@project.delta/60, 'hour')
    =pluralize(@project.delta%60, 'minute')

app/views/projects/show.html.haml
.page-header
  %h2
    = @project.name

    %small
      .pull-right
        -if can? :report, @project
          = link_to "Report", report_project_path(@project, @task), target:"_blank", class:'btn'
          / - monday = Time.now.to_date - ((Time.now.wday + 6) % 7).day 
          / = link_to "Report last week", report_project_path(@project, @task, week: monday - 1.week), target:"_blank", class:'btn'
          / = link_to "Report of current week", report_project_path(@project, @task, week: monday), target:"_blank", class:'btn'
        -if can? :manage, @project
          .btn-group
            %a.btn.btn-warning{href: edit_project_path(@project)}
              %i.icon-pencil.icon-white
              Edit
            %a.btn.btn-danger{"data-confirm" => "Are you sure?", "data-method" => "delete", href: project_path(@project), rel: "nofollow"}
              %i.icon-remove.icon-white
              Delete


.row
  .span9
    -if can? :manage, User
      - @project.product_owners.each do |user|
        .pull-left
          .btn-group
            %a.btn{href:user_path(user)}= user
            =link_to "&times;".html_safe(), rol_project_path(@project, user: user, rol: :product_owner), method: :delete, class: "btn"
          &nbsp;


      %form{"accept-charset" => "UTF-8", :action => rol_project_path(@project), :method => "post", :class=> "form-inline pull-left"}
        %input{:name => "utf8", :type => "hidden", :value => "✓"}
        %input{:name => "authenticity_token", :type => "hidden", :value => form_authenticity_token}
        %select#rol_user{:name => "user"}
          - User.all.each do |user|
            %option{:value => user.id}= user
        %input#rol_rol{:name => "rol", :type => "hidden", :value => "product_owner"}
          %input{:name => "commit", :type => "submit", :value => "Add Product Owner", class: "btn"}


-if @sprint
  %h3
    Current Sprint
    -if @sprint
      %small (#{@sprint})
  -if @task_current_sprint.present?
    #tasks.sortable
      =render @task_current_sprint
    .pull-right
      .grey-points.sum
        .sum-label
          Total:
        = "%g" % @task_current_sprint.collect{|t| t.finished ? t.points || 0 : 0}.sum
        \ /
        = "%g" % @task_current_sprint.collect{|t| t.points || 0}.sum
  -else
    .row.task
      No task here

-else
  %h3
    No Current Sprint
  -if can? :create, Sprint
    %center.form-actions
      %a.btn.btn-primary.btn-large{href: new_sprint_path}
        %span.span4 New Sprint
      
%h3 icebox
-if @project.tasks.icebox.present?
  #icebox.sortable
    =render @project.tasks.icebox, icebox: true, sortable: true
-else
  .row.task
    No task here

.row
  =simple_form_for((@task || :task), url:suggest_project_tasks_path(@project), html: {class: "form-box span6 offset1"}) do |f|
    Tarea: 
    = f.text_field :name, class: 'span3'
    .pull-right
      = f.select(:category, Task::CATEGORIES )
    %label
      Description:
    = f.text_area :description, :size => "25x3", class: 'span6'
    .form-actions
      .pull-right
        = f.submit class:'btn btn-primary'

%br
.pull-right
  -if can? :create, @project.tasks.build
    %a.btn.btn-primary{href:new_project_task_path(@project)} New Task 

= link_to 'Back', projects_path, class: 'btn' 

#chart
-if @chart
  = render_chart(@chart, 'chart')


- if can? :index, Sprint
  %h5 Recent Sprints
  %nav
    %ul.nav.nav-tabs.nav-stacked
      - Sprint.all.each do |sprint|
        %li= link_to sprint, sprint_project_path(@project, sprint)