config/routes.rb
Kiwitime::Application.routes.draw do

  resources :sprints do
    resources :workings
  end

  devise_scope :user do
    get 'users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/p/:project_id/tasks" => redirect("/p/%{project_id}")
  get "/p/:project_id/tasks/:task_id/sittings" => redirect("/p/%{project_id}/tasks/%{task_id}")

  resources :users, path: 'u' do
    get 'page/:page' => :index, on: :collection
    post 'rol' => :set_rol, on: :member
    delete 'rol' => :set_rol, on: :member
  end

  resources :tasks, only: [] do
    post :sort, on: :collection
  end

  resources :projects, path: 'p' do
    post 'rol' => :set_rol, on: :member
    delete 'rol' => :delete_rol, on: :member
    resources :tasks do
      post :suggest, on: :collection
      resources :sittings
      resources :comments, except: :index
      member do
        get 'finish'
        get 'reject'
        get 'start'
        get 'stop'
        get 'up'
        get 'accept'
      end
    end

    member do
      get 'report'
      get 'sprint/:sprint_id' => :sprint, as: :sprint
    end
  end

  authenticated do
    root to: "projects#index"
  end

  devise_scope :user do
    root :to => "pages#home"
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Kiwitime!
    = stylesheet_link_tag    "application", :media => "all"
    = stylesheet_link_tag    "bootstrap", :media => "all"
    = javascript_include_tag "http://code.jquery.com/jquery-1.8.3.js", "http://code.jquery.com/ui/1.9.2/jquery-ui.js"#, "rails.js"
    = javascript_include_tag "application"
    %script{:src => "http://www.google.com/jsapi"}
    = yield :javascript
    = csrf_meta_tags
  %body

    .container
      .navbar
        .navbar-inner
          %a.brand{href:"/"}
            Kiwitime!

          %ul.nav.pull-right
            -if user_signed_in?
              %li
                %a{:href => user_path(current_user)}
                  =gravatar_for current_user, size: 30
                  #{current_user.name}
              %li
                %a{:href => edit_user_path(current_user)} Settings
              %li
                - #%a{:href => destroy_user_session_path, :method => :delete} Sign out
                = link_to "Sign out", destroy_user_session_path, :method => :delete
            -else
              -# %li
              -#   = link_to "Sign up", new_user_registration_path
              -# %li
              -#   %a{:href => new_user_session_path} Sign in
              %li
                = link_to "Sign up/in with Google", user_omniauth_authorize_path(:google_oauth2)

              %li
                = link_to "Sign up", new_user_registration_path, class: "sign"
              %li
                %a or
              %li
                = link_to "sign in", new_user_session_path, class: "sign"

                =# link_to (image_tag "github_32.png"), user_omniauth_authorize_path(:github)
                \
                =# link_to (image_tag "google_32.png"), user_omniauth_authorize_path(:google_oauth2)
                \
                =# link_to (image_tag "twitter_32.png"), user_omniauth_authorize_path(:twitter)


    .container
      .row
        - if @fullpage
          .span12
            = render 'shared/alerts'
            = yield
        - else
          .span3
            %nav
              %ul.nav.nav-tabs.nav-stacked
                - if can? :read, User
                  %li
                    = link_to "Users", users_path
                - if can? :read, Project
                  %li
                    = link_to "Projects", projects_path
                - if can? :index, Sprint
                  %li
                    = link_to "Sprints", sprints_path

            - if can? :index, Project
              %h5 Projects
              %nav
                %ul.nav.nav-tabs.nav-stacked
                  - Project.accessible_by(current_ability).each do |project|
                    %li= link_to project, project_path(project)

            - if can? :index, Sprint
              %h5 Recent Sprints
              %nav
                %ul.nav.nav-tabs.nav-stacked
                  - Sprint.all.each do |sprint|
                    %li= link_to sprint, sprint_path(sprint)

          .span9
            = render 'shared/alerts'
            = yield

    %footer
      .container
        %br
        %br
        %br

    -# javascript_include_tag "bootstrap-datepicker"



-#    - if has_content?(:sidebar)
-#          .span3
-#            = yield(:sidebar)
-#          .span9
-#            = yield
-#        - else
-#          .span12
-#          = yield